spring:
  application:
    name: ai-service

  mongodb:
    uri: mongodb://admin:admin@localhost:27017/airecomentationfitness?authSource=admin

  kafka:
    bootstrap-servers: localhost:9094

    consumer:
      group-id: activity-processor-group

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.fitness.aiservice.model.Activity
        spring.json.trusted.packages: "*"

kafka:
  topic:
    name: activity-events

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

gemini:
  api:
    url: ${GEMINI_URL}
    key: ${GEMINI_API}

server:
  port: 9093