spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5000/fitness-db
    username: admin_user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
server:
  port: 9091